server:
  port: 8084
  servlet:
    context-path: /media

spring:
  application:
    name: media_service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

jwt:
  issuer: com.shibana.identity_service
  access:
    secret-key: ${JWT_ACCESS_SECRET_KEY}


logging:
  level:
    org.springframework: INFO
    com.shibana.media_service: INFO
    io.lettuce.core: INFO