server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1/profile

spring:
  # =========================
  #   App & Server
  # =========================
  application:
    name: profile_service

  # =========================
  #   Database - Neo4j
  # =========================
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:neo4j}
