server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profile_service

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

jwt:
  issuer: com.shibana.identity_service
  access:
    secret-key: ${JWT_ACCESS_SECRET_KEY}

logging:
  level:
    org.springframework: INFO
    com.shibana.profile_service: DEBUG
    io.lettuce.core: INFO